apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: globomantics-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        cluster: https://kubernetes.default.svc
      - env: staging
        cluster: https://kubernetes.default.svc
      - env: prod
        cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: 'globomantics-app-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jgrecu/ps-implementing-gitops.git
        targetRevision: HEAD
        path: 'apps/{{env}}'
      destination:
        server: '{{cluster}}'
        namespace: 'globomantics-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true